# Generated by Django 3.2.6 on 2021-08-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ism', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vaqti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input_per', models.ImageField(null=True, upload_to='kunlik/')),
                ('Output_per', models.ImageField(null=True, upload_to='kunlik/')),
                ('Vaqti_in', models.DateTimeField(null=True)),
                ('Vaqti_out', models.DateTimeField(null=True)),
                ('PesonId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face_detect.person')),
            ],
        ),
    ]
